"""add lot_number and location to part_lots, warehouse transfers

Revision ID: 3c2a7f430a7e
Revises: 845869315755
Create Date: 2026-08-27 12:06:36.136705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2a7f430a7e'
down_revision: Union[str, Sequence[str], None] = '845869315755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('origin_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PEDIDO', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA', name='warehouse_transfer_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_transfers_filial_id'), 'warehouse_transfers', ['filial_id'], unique=False)
    op.create_table('warehouse_transfer_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['warehouse_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_transfer_lines_transfer_id'), 'warehouse_transfer_lines', ['transfer_id'], unique=False)
    op.add_column('part_lots', sa.Column('lot_number', sa.Integer(), nullable=True))
    op.add_column('part_lots', sa.Column('location', sa.String(length=30), nullable=True))
    op.add_column('stock_movements', sa.Column('reference', sa.String(length=80), nullable=True))
    op.add_column('stock_movements', sa.Column('responsible_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'users', ['responsible_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'responsible_user_id')
    op.drop_column('stock_movements', 'reference')
    op.drop_column('part_lots', 'location')
    op.drop_column('part_lots', 'lot_number')
    op.drop_index(op.f('ix_warehouse_transfer_lines_transfer_id'), table_name='warehouse_transfer_lines')
    op.drop_table('warehouse_transfer_lines')
    op.drop_index(op.f('ix_warehouse_transfers_filial_id'), table_name='warehouse_transfers')
    op.drop_table('warehouse_transfers')
    # ### end Alembic commands ###
