"""create dealership_vehicles and vehicle_sales tables

Revision ID: 4509c2cf09de
Revises: 3c2a7f430a7e
Create Date: 2026-08-27 13:50:52.561813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4509c2cf09de'
down_revision: Union[str, Sequence[str], None] = '3c2a7f430a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealership_vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('EN_TRANSITO', 'DISPONIBLE', 'EN_PREPARACION', 'RESERVADO', 'VENDIDO', name='dealership_vehicle_status'), nullable=False),
    sa.Column('condition', sa.Enum('NUEVO', 'USADO', name='dealership_vehicle_condition'), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.Enum('GASOLINA', 'DIESEL', 'HIBRIDO', 'ELECTRICO', name='dealership_vehicle_fuel_type'), nullable=True),
    sa.Column('transmission', sa.Enum('AUTOMATICA', 'MANUAL', name='dealership_vehicle_transmission'), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=True),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('price_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_financed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealership_vehicles_filial_id'), 'dealership_vehicles', ['filial_id'], unique=False)
    op.create_table('vehicle_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('client_document', sa.String(length=20), nullable=True),
    sa.Column('advisor_user_id', sa.UUID(), nullable=True),
    sa.Column('sale_type', sa.Enum('CONTADO', 'FINANCIADO', name='vehicle_sale_type'), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['dealership_vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_sales_filial_id'), 'vehicle_sales', ['filial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_sales_filial_id'), table_name='vehicle_sales')
    op.drop_table('vehicle_sales')
    op.drop_index(op.f('ix_dealership_vehicles_filial_id'), table_name='dealership_vehicles')
    op.drop_table('dealership_vehicles')
    # ### end Alembic commands ###
