"""create parts, part_sales, part_sale_lines and part_returns tables

Revision ID: 464ef496cebf
Revises: b8c7d46085b7
Create Date: 2026-08-26 22:27:56.405191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464ef496cebf'
down_revision: Union[str, Sequence[str], None] = 'b8c7d46085b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('client_document', sa.String(length=20), nullable=True),
    sa.Column('request_reason', sa.String(length=150), nullable=False),
    sa.Column('discount_label', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PEDIDO', 'COMPLETADO', 'CANCELADO', name='part_sale_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_sales_filial_id'), 'part_sales', ['filial_id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability', sa.Enum('DISPONIBLE', 'AGOTADO', name='part_availability'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_filial_id'), 'parts', ['filial_id'], unique=False)
    op.create_table('part_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.Enum('NUEVO', 'USADO', 'DEFECTUOSO', name='return_condition'), nullable=False),
    sa.Column('origin_warehouse', sa.String(length=60), nullable=False),
    sa.Column('destination_warehouse', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('PEDIDO_EN_EXCESO', 'DEFECTUOSO', 'REPUESTO_INCORRECTO', 'OTRO', name='return_reason'), nullable=False),
    sa.Column('reason_notes', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_returns_filial_id'), 'part_returns', ['filial_id'], unique=False)
    op.create_table('part_sale_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_sale_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_sale_id'], ['part_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_sale_lines_part_sale_id'), 'part_sale_lines', ['part_sale_id'], unique=False)
    op.create_table('preliminary_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('inspector_user_id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EN_PROCESO', 'COMPLETADA', name='inspection_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preliminary_inspections_filial_id'), 'preliminary_inspections', ['filial_id'], unique=False)
    op.create_index(op.f('ix_preliminary_inspections_service_order_id'), 'preliminary_inspections', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_preliminary_inspections_vehicle_id'), 'preliminary_inspections', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preliminary_inspections_vehicle_id'), table_name='preliminary_inspections')
    op.drop_index(op.f('ix_preliminary_inspections_service_order_id'), table_name='preliminary_inspections')
    op.drop_index(op.f('ix_preliminary_inspections_filial_id'), table_name='preliminary_inspections')
    op.drop_table('preliminary_inspections')
    op.drop_index(op.f('ix_part_sale_lines_part_sale_id'), table_name='part_sale_lines')
    op.drop_table('part_sale_lines')
    op.drop_index(op.f('ix_part_returns_filial_id'), table_name='part_returns')
    op.drop_table('part_returns')
    op.drop_index(op.f('ix_parts_filial_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_part_sales_filial_id'), table_name='part_sales')
    op.drop_table('part_sales')
    # ### end Alembic commands ###
