"""add vehicle sale sequence, part sale line unit_cost

Revision ID: 4e479192a548
Revises: ff6422935b8a
Create Date: 2026-08-28 10:17:55.482081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e479192a548'
down_revision: Union[str, Sequence[str], None] = 'ff6422935b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_sale_lines', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('vehicle_sales', sa.Column('sequence_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_sales', 'sequence_number')
    op.drop_column('part_sale_lines', 'unit_cost')
    # ### end Alembic commands ###
