"""add stock_quantity and min_stock to parts

Revision ID: 4f444e776257
Revises: 464ef496cebf
Create Date: 2026-08-26 22:39:50.913671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f444e776257'
down_revision: Union[str, Sequence[str], None] = '464ef496cebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('parts', sa.Column('min_stock', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'min_stock')
    op.drop_column('parts', 'stock_quantity')
    # ### end Alembic commands ###
