"""add part_id to tempario_parts

Revision ID: 4fcb0f5c54c9
Revises: da7b2a4ef077
Create Date: 2026-08-26 23:17:28.873641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcb0f5c54c9'
down_revision: Union[str, Sequence[str], None] = 'da7b2a4ef077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tempario_parts', sa.Column('part_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tempario_parts', 'parts', ['part_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tempario_parts', type_='foreignkey')
    op.drop_column('tempario_parts', 'part_id')
    # ### end Alembic commands ###
