"""create roles and role_module_permissions tables

Revision ID: 57284de9ea61
Revises: e471a941ac1c
Create Date: 2026-08-25 23:54:51.162126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57284de9ea61'
down_revision: Union[str, Sequence[str], None] = 'e471a941ac1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Enum('PLATFORM', 'HOLDING', 'FILIAL', name='role_scope'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('role_module_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('access', sa.Enum('VER', 'EDITAR', name='access_level'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_module')
    )
    op.create_index(op.f('ix_role_module_permissions_role_id'), 'role_module_permissions', ['role_id'], unique=False)
    op.drop_constraint(op.f('uq_filiales_holding_id_slug'), 'filiales', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_filiales_holding_id_slug'), 'filiales', ['holding_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_role_module_permissions_role_id'), table_name='role_module_permissions')
    op.drop_table('role_module_permissions')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
