"""create administracion tables and add vehicle cost_price

Revision ID: 5f7d1924fd32
Revises: 4509c2cf09de
Create Date: 2026-08-27 14:48:48.946995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7d1924fd32'
down_revision: Union[str, Sequence[str], None] = '4509c2cf09de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.Enum('USD', 'BS', name='account_currency'), nullable=False),
    sa.Column('account_type', sa.Enum('CORRIENTE', 'AHORRO', 'CAJA', name='account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_filial_id'), 'accounts', ['filial_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('trade_name', sa.String(length=150), nullable=True),
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('supplier_type', sa.Enum('FABRICANTE', 'NACIONAL', 'IMPORTADOR', name='supplier_type'), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', name='supplier_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_filial_id'), 'suppliers', ['filial_id'], unique=False)
    op.create_table('expense_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('NOMINA_COMISIONES', 'SERVICIOS', 'COMPRAS_PROVEEDORES', 'ALQUILER', 'MANTENIMIENTO', 'MARKETING', 'IMPUESTOS_TASAS', 'OTRO', name='expense_category'), nullable=False),
    sa.Column('beneficiary', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'BS', name='account_currency'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('registered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_entries_filial_id'), 'expense_entries', ['filial_id'], unique=False)
    op.create_table('income_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('AUTOMATICO', 'MANUAL', name='income_source'), nullable=False),
    sa.Column('origin_reference', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'BS', name='account_currency'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('registered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_entries_filial_id'), 'income_entries', ['filial_id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ENVIADA', 'COTIZADA', 'PAGADA', 'RECIBIDA', 'CONCILIADA', 'CANCELADA', name='purchase_request_status'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_filial_id'), 'purchase_requests', ['filial_id'], unique=False)
    op.create_table('supplier_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE_ENVIO', 'ENVIADO', 'APROBADO', 'RECHAZADO', 'RESUELTO', name='claim_status'), nullable=False),
    sa.Column('return_reference', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_claims_filial_id'), 'supplier_claims', ['filial_id'], unique=False)
    op.create_table('purchase_request_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_request_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_request_lines_purchase_request_id'), 'purchase_request_lines', ['purchase_request_id'], unique=False)
    op.add_column('dealership_vehicles', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealership_vehicles', 'cost_price')
    op.drop_index(op.f('ix_purchase_request_lines_purchase_request_id'), table_name='purchase_request_lines')
    op.drop_table('purchase_request_lines')
    op.drop_index(op.f('ix_supplier_claims_filial_id'), table_name='supplier_claims')
    op.drop_table('supplier_claims')
    op.drop_index(op.f('ix_purchase_requests_filial_id'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_income_entries_filial_id'), table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_index(op.f('ix_expense_entries_filial_id'), table_name='expense_entries')
    op.drop_table('expense_entries')
    op.drop_index(op.f('ix_suppliers_filial_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_accounts_filial_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
