"""create warehouses, part_lots and stock_movements tables

Revision ID: 845869315755
Revises: ffba2b2de8b3
Create Date: 2026-08-27 11:17:01.179454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845869315755'
down_revision: Union[str, Sequence[str], None] = 'ffba2b2de8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_filial_id'), 'warehouses', ['filial_id'], unique=False)
    op.create_table('part_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_lots_filial_id'), 'part_lots', ['filial_id'], unique=False)
    op.create_index(op.f('ix_part_lots_part_id'), 'part_lots', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_lots_warehouse_id'), 'part_lots', ['warehouse_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('ENTRADA', 'TRANSFERENCIA_SALIDA', 'TRANSFERENCIA_ENTRADA', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_filial_id'), 'stock_movements', ['filial_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_part_id'), 'stock_movements', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_part_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_filial_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_part_lots_warehouse_id'), table_name='part_lots')
    op.drop_index(op.f('ix_part_lots_part_id'), table_name='part_lots')
    op.drop_index(op.f('ix_part_lots_filial_id'), table_name='part_lots')
    op.drop_table('part_lots')
    op.drop_index(op.f('ix_warehouses_filial_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
