"""add completed_by_user_id to warehouse transfers

Revision ID: 921954f10182
Revises: 6f3f68db6f9b
Create Date: 2026-08-27 23:01:59.959764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921954f10182'
down_revision: Union[str, Sequence[str], None] = '6f3f68db6f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order_transfers', sa.Column('fulfilled_by_user_id', sa.UUID(), nullable=True))
    op.add_column('service_order_transfers', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'service_order_transfers', 'users', ['fulfilled_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('service_orders', sa.Column('advisor_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'service_orders', 'users', ['advisor_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_column('service_orders', 'advisor_user_id')
    op.drop_constraint(None, 'service_order_transfers', type_='foreignkey')
    op.drop_column('service_order_transfers', 'fulfilled_at')
    op.drop_column('service_order_transfers', 'fulfilled_by_user_id')
    # ### end Alembic commands ###
