"""add scheduled_at to service_orders

Revision ID: b8c7d46085b7
Revises: fc9f2009dc56
Create Date: 2026-08-26 16:59:57.476651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c7d46085b7'
down_revision: Union[str, Sequence[str], None] = 'fc9f2009dc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'scheduled_at')
    # ### end Alembic commands ###
