"""create labor_settings, temparios and tempario_parts tables

Revision ID: da7b2a4ef077
Revises: 4f444e776257
Create Date: 2026-08-26 23:00:28.572296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7b2a4ef077'
down_revision: Union[str, Sequence[str], None] = '4f444e776257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igtf_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bcv_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_settings_filial_id'), 'labor_settings', ['filial_id'], unique=True)
    op.create_table('temparios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('MANTENIMIENTO_PREVENTIVO', 'FRENOS', 'SUSPENSION', 'TRANSMISION', 'NEUMATICOS', 'MOTOR', 'ELECTRICO', 'AIRE_ACONDICIONADO', 'OTRO', name='tempario_category'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('compatible_vehicles', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('requires_parts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temparios_filial_id'), 'temparios', ['filial_id'], unique=False)
    op.create_table('tempario_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tempario_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tempario_id'], ['temparios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tempario_parts_tempario_id'), 'tempario_parts', ['tempario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tempario_parts_tempario_id'), table_name='tempario_parts')
    op.drop_table('tempario_parts')
    op.drop_index(op.f('ix_temparios_filial_id'), table_name='temparios')
    op.drop_table('temparios')
    op.drop_index(op.f('ix_labor_settings_filial_id'), table_name='labor_settings')
    op.drop_table('labor_settings')
    # ### end Alembic commands ###
