"""create filiales table

Revision ID: e471a941ac1c
Revises: 4c9c3dff654f
Create Date: 2026-08-25 23:51:12.473397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e471a941ac1c'
down_revision: Union[str, Sequence[str], None] = '4c9c3dff654f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filiales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(
    "uq_filiales_holding_id_slug", "filiales", ["holding_id", "slug"])
    op.create_index(op.f('ix_filiales_holding_id'), 'filiales', ['holding_id'], unique=False)
    op.create_index(op.f('ix_filiales_slug'), 'filiales', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filiales_slug'), table_name='filiales')
    op.drop_index(op.f('ix_filiales_holding_id'), table_name='filiales')
    op.drop_table('filiales')
    op.drop_constraint("uq_filiales_holding_id_slug", "filiales", type_="unique")
    # ### end Alembic commands ###
