"""create clients and vehicles tables

Revision ID: e7a36bbe1cab
Revises: b87901215915
Create Date: 2026-08-26 14:51:28.334633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a36bbe1cab'
down_revision: Union[str, Sequence[str], None] = 'b87901215915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('client_type', sa.Enum('PARTICULAR', 'EMPRESA', name='client_type'), nullable=False),
    sa.Column('document_type', sa.Enum('V', 'J', 'E', 'G', name='document_type'), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('contact_preference', sa.Enum('WHATSAPP', 'LLAMADA', 'CORREO', 'SMS', name='contact_preference'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('address_type', sa.Enum('HOGAR', 'TRABAJO', 'OTRO', name='address_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_filial_id'), 'clients', ['filial_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('body_type', sa.String(length=40), nullable=True),
    sa.Column('plate', sa.String(length=8), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('upholstery', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.Enum('GASOLINA', 'DIESEL', 'HIBRIDO', 'ELECTRICO', name='fuel_type'), nullable=True),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATICA', name='transmission_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_client_id'), 'vehicles', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_client_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_clients_filial_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
