"""create upsells table

Revision ID: ee9f0db9c15d
Revises: 4e479192a548
Create Date: 2026-08-28 10:57:52.198608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9f0db9c15d'
down_revision: Union[str, Sequence[str], None] = '4e479192a548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upsells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'APROBADO', 'POSPUESTO', 'RECHAZADO', name='upsell_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upsells_service_order_id'), 'upsells', ['service_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upsells_service_order_id'), table_name='upsells')
    op.drop_table('upsells')
    # ### end Alembic commands ###
