"""create bays and service_orders tables

Revision ID: fc9f2009dc56
Revises: e7a36bbe1cab
Create Date: 2026-08-26 15:29:02.699359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9f2009dc56'
down_revision: Union[str, Sequence[str], None] = 'e7a36bbe1cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bays_filial_id'), 'bays', ['filial_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADO', 'ORDEN_CERRADA', 'CANCELADO', name='service_order_status'), nullable=False),
    sa.Column('order_type', sa.Enum('REGULAR', 'MPT', name='service_order_type'), nullable=False),
    sa.Column('technician_user_id', sa.UUID(), nullable=True),
    sa.Column('bay_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bay_id'], ['bays.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_filial_id'), 'service_orders', ['filial_id'], unique=False)
    op.create_index(op.f('ix_service_orders_vehicle_id'), 'service_orders', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_orders_vehicle_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_filial_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_bays_filial_id'), table_name='bays')
    op.drop_table('bays')
    # ### end Alembic commands ###
