"""add completed_by_user_id to warehouse transfers

Revision ID: ff6422935b8a
Revises: 921954f10182
Create Date: 2026-08-27 23:06:07.302486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6422935b8a'
down_revision: Union[str, Sequence[str], None] = '921954f10182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_transfers', sa.Column('completed_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'warehouse_transfers', 'users', ['completed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_transfers', type_='foreignkey')
    op.drop_column('warehouse_transfers', 'completed_by_user_id')
    # ### end Alembic commands ###
