"""add iva_percentage, service order tasks, transfers and total_amount

Revision ID: ffba2b2de8b3
Revises: 4fcb0f5c54c9
Create Date: 2026-08-27 10:16:43.669316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffba2b2de8b3'
down_revision: Union[str, Sequence[str], None] = '4fcb0f5c54c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_order_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('tempario_id', sa.UUID(), nullable=False),
    sa.Column('code_snapshot', sa.String(length=20), nullable=False),
    sa.Column('name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('hours_snapshot', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'COMPLETADA', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tempario_id'], ['temparios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_tasks_service_order_id'), 'service_order_tasks', ['service_order_id'], unique=False)
    op.create_table('service_order_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PEDIDO', name='transfer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_transfers_service_order_id'), 'service_order_transfers', ['service_order_id'], unique=False)
    op.create_table('service_order_transfer_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['service_order_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_transfer_lines_transfer_id'), 'service_order_transfer_lines', ['transfer_id'], unique=False)
    op.add_column('labor_settings', sa.Column('iva_percentage', sa.Numeric(precision=5, scale=2), nullable=False, server_default='16'))
    op.add_column('service_orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'total_amount')
    op.drop_column('labor_settings', 'iva_percentage')
    op.drop_index(op.f('ix_service_order_transfer_lines_transfer_id'), table_name='service_order_transfer_lines')
    op.drop_table('service_order_transfer_lines')
    op.drop_index(op.f('ix_service_order_transfers_service_order_id'), table_name='service_order_transfers')
    op.drop_table('service_order_transfers')
    op.drop_index(op.f('ix_service_order_tasks_service_order_id'), table_name='service_order_tasks')
    op.drop_table('service_order_tasks')
    # ### end Alembic commands ###
